import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { pretendard, partialSans } from "@/public/fonts"; // 방금 만든 설정 불러오기
import { Toaster } from "react-hot-toast";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ko"
      className={`${pretendard.variable} ${partialSans.variable}`}
    >
      <body className={pretendard.className}>
        <Toaster toastOptions={{ duration: 1500, removeDelay: 1000 }} />
        {children}
      </body>
    </html>
  );
}
